In [1]:
faqs="""### **Caption for YouTube Video**
**"Unveiling Nature's Rainbow: The Stunning Beauty of Colorful Birds! 🌈🦜 | You Won't Believe Your Eyes!"**

### **Speech Script for the Video**

*(Opening Scene: A vibrant, colorful bird perched on a tree or flying in its natural habitat)*

**"Hey everyone, welcome back to our channel! In today’s video, we’re diving into one of nature’s most mesmerizing treasures: the colorful birds that paint the sky with their stunning hues. From the deep reds of the scarlet macaw to the electric blues of the kingfisher, we’re going to explore these feathered wonders up close and personal. 🌟"**

*(Showcase close-up shots of different birds, highlighting their vibrant feathers)*

**"Did you know that some of these birds use their dazzling colors to communicate with each other? Whether it’s for mating, warding off predators, or simply expressing their dominance, these birds are truly the superheroes of the animal kingdom. 🦸‍♂️🦸‍♀️"**

*(Cut to a bird in flight)*

**"But it’s not just their looks that make them extraordinary – many of these species have incredible adaptations that help them thrive in some of the most challenging environments on Earth. Imagine being able to navigate vast distances or blend in perfectly with your surroundings – that’s the true magic of these colorful birds!"**

*(Cut to birds interacting, singing, or in their natural environment)*

**"So, sit back, relax, and get ready to be amazed by the beauty and brilliance of nature. Don't forget to like, share, and subscribe if you want to see more stunning wildlife content! Hit that bell icon so you never miss a moment of wonder!"**

*(Ending Scene: Slow-motion footage of the bird flying away or perched beautifully in a tree)*

**"Thanks for watching, and remember – every bird you see is a piece of the natural world’s masterpiece. Until next time, keep exploring!"**

---

### **Key Points for Virality:**

1. **Emotion & Awe:** The speech should evoke awe and curiosity about the birds' beauty and abilities.
2. **Engagement:** Encourage viewers to like, comment, and share the video to increase engagement.
3. **Call to Action:** Remind viewers to subscribe and hit the bell icon for more content.
4. **Brevity & Energy:** Keep the script energetic and concise, allowing the visuals to take center stage while adding value through your narration.

This combination of a catchy title and an engaging, informative script will help maximize the video's potential to go viral!"""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
tokenizer=Tokenizer()

In [4]:
tokenizer.fit_on_texts([faqs])   #Convert text to word

In [5]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'of': 3,
 'and': 4,
 'birds': 5,
 'a': 6,
 'in': 7,
 'for': 8,
 'their': 9,
 'you': 10,
 'or': 11,
 'that': 12,
 'these': 13,
 'video': 14,
 'colorful': 15,
 'bird': 16,
 'stunning': 17,
 'beauty': 18,
 'your': 19,
 'script': 20,
 'natural': 21,
 'with': 22,
 '–': 23,
 'speech': 24,
 'scene': 25,
 'vibrant': 26,
 'perched': 27,
 'on': 28,
 'tree': 29,
 'flying': 30,
 'back': 31,
 'we’re': 32,
 'most': 33,
 'up': 34,
 'close': 35,
 'some': 36,
 'it’s': 37,
 'cut': 38,
 'them': 39,
 'help': 40,
 'so': 41,
 'like': 42,
 'share': 43,
 'subscribe': 44,
 'see': 45,
 'more': 46,
 'content': 47,
 'hit': 48,
 'bell': 49,
 'icon': 50,
 'keep': 51,
 'awe': 52,
 'engagement': 53,
 'viewers': 54,
 'caption': 55,
 'youtube': 56,
 'unveiling': 57,
 "nature's": 58,
 'rainbow': 59,
 '🌈🦜': 60,
 "won't": 61,
 'believe': 62,
 'eyes': 63,
 'opening': 64,
 'its': 65,
 'habitat': 66,
 'hey': 67,
 'everyone': 68,
 'welcome': 69,
 'our': 70,
 'channel': 71,
 'today’s': 72,
 'diving': 73,


In [6]:
len(tokenizer.word_index)

236

In [7]:
input_sequences=[]
for sentence in faqs.split('\n'):
  #print(sentence)
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [8]:
input_sequences

[[55, 8],
 [55, 8, 56],
 [55, 8, 56, 14],
 [57, 58],
 [57, 58, 59],
 [57, 58, 59, 1],
 [57, 58, 59, 1, 17],
 [57, 58, 59, 1, 17, 18],
 [57, 58, 59, 1, 17, 18, 3],
 [57, 58, 59, 1, 17, 18, 3, 15],
 [57, 58, 59, 1, 17, 18, 3, 15, 5],
 [57, 58, 59, 1, 17, 18, 3, 15, 5, 60],
 [57, 58, 59, 1, 17, 18, 3, 15, 5, 60, 10],
 [57, 58, 59, 1, 17, 18, 3, 15, 5, 60, 10, 61],
 [57, 58, 59, 1, 17, 18, 3, 15, 5, 60, 10, 61, 62],
 [57, 58, 59, 1, 17, 18, 3, 15, 5, 60, 10, 61, 62, 19],
 [57, 58, 59, 1, 17, 18, 3, 15, 5, 60, 10, 61, 62, 19, 63],
 [24, 20],
 [24, 20, 8],
 [24, 20, 8, 1],
 [24, 20, 8, 1, 14],
 [64, 25],
 [64, 25, 6],
 [64, 25, 6, 26],
 [64, 25, 6, 26, 15],
 [64, 25, 6, 26, 15, 16],
 [64, 25, 6, 26, 15, 16, 27],
 [64, 25, 6, 26, 15, 16, 27, 28],
 [64, 25, 6, 26, 15, 16, 27, 28, 6],
 [64, 25, 6, 26, 15, 16, 27, 28, 6, 29],
 [64, 25, 6, 26, 15, 16, 27, 28, 6, 29, 11],
 [64, 25, 6, 26, 15, 16, 27, 28, 6, 29, 11, 30],
 [64, 25, 6, 26, 15, 16, 27, 28, 6, 29, 11, 30, 7],
 [64, 25, 6, 26, 15, 16, 2

In [9]:
max_length=max([len(x) for x in input_sequences])

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences, maxlen=max_length,padding='pre')

In the below code we are removing the last column for the matrix to predict the word

In [11]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  55,   8],
       [  0,   0,   0, ...,  55,   8,  56],
       [  0,   0,   0, ...,   8,  56,  14],
       ...,
       [  0,   0,   0, ..., 233, 234,   2],
       [  0,   0,   0, ..., 234,   2, 235],
       [  0,   0,   0, ...,   2, 235, 236]], dtype=int32)

In [12]:
padded_input_sequences[:,:-1]

array([[  0,   0,   0, ...,   0,   0,  55],
       [  0,   0,   0, ...,   0,  55,   8],
       [  0,   0,   0, ...,  55,   8,  56],
       ...,
       [  0,   0,   0, ...,   1, 233, 234],
       [  0,   0,   0, ..., 233, 234,   2],
       [  0,   0,   0, ..., 234,   2, 235]], dtype=int32)

In [13]:
x=padded_input_sequences[:,:-1]

In [14]:
y=padded_input_sequences[:,-1]

In [15]:
y.shape

(375,)

We will apply One Hot Encooding for the input example if the sentence is       
"Hi my name is ABC I live in xyx"
Total 9 words, to predict my  in the above sentence
 **[0 1 0 0 0 0 0 0 0]** in case we need

 if the output is [ 0.1 **0.6** 0.1 0.1 0.1 0.1 0.1 0.1 0.1] then we will take the second word because it has the highest probability

In [16]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y, num_classes=237)

In [17]:
y.shape

(375, 283)

In [18]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [20]:
model=Sequential()
model.add(Embedding(237,100, input_length=56))
model.add(LSTM(150))
model.add(Dense(237,activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
x.shape

(375, 56)

In [22]:
y.shape

(375, 283)

In [23]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.fit(x,y,epochs=100)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 5s 92ms/step - accuracy: 0.0183 - loss: 5.6419
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 85ms/step - accuracy: 0.0670 - loss: 5.4656
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.0316 - loss: 5.1569
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 90ms/step - accuracy: 0.0682 - loss: 4.9999
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 87ms/step - accuracy: 0.0635 - loss: 5.0208
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.0592 - loss: 5.0313
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - accuracy: 0.0829 - loss: 4.9229
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 159ms/step - accuracy: 0.0662 - loss: 4.8170
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 146ms/step - accuracy: 0.0824 - loss: 4.8135
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - accuracy: 0.0787 - loss: 4.8289
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - accuracy: 0.1106 - loss: 4.6910
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 90ms/st

In [39]:
import numpy
import time
text="Ending"

for i in range(10):

  #tokenize

  token_text=tokenizer.texts_to_sequences([text])[0]

  #padding
  padded_token_text = pad_sequences([token_text],maxlen=56,padding='pre')
  print(padded_token_text)

  model.predict(padded_token_text).shape
  position=np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index== position:
      text=text + " " + word
      print(text)
      time.sleep(1)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0 172]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
Ending scene
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  172  25]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Ending scene slow
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 172
   25 173]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Ending scene slow motion
[[  0   0   0 

In [28]:
import numpy as np